---
title: "DSEM demo videos: Supporting materials"
author: "Ellen Hamaker"
date: "Last update: November, 2022"
mainfont: Arial
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    df_print: paged
    theme: spacelab
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '5'
font_size: 19pt
urlcolor: green
params:
  rcode: true
  answers: true
---

$~$

This page contains the Mplus input and output files, and the simulated data files that are used for the DSEM demo videos.

$~$

# Introduction
Dynamics structural equation modeling (DSEM) is based on a combination of time series modeling, multilevel modeling, and structural equation modeling. It can be used to analyze time series data and intensive longitudinal data, such as obtained with daily diaries, ecological momentary assessments, experience sampling, ambulatory assessments, and other techniques that tend to result in (relatively) large numbers of repeated measures (say, more than 20) per case. 

More information about DSEM and how it was implemented in the software package Mplus can be found here: https://ellenhamaker.github.io/DSEM-book-chapter/ and here: https://www.statmodel.com/TimeSeries.shtml.


$~$ 

# DSEM models 
The DSEM demo videos show how to use Mplus to specify specific models, and how to interpret the output. In addition, there are also videos that focus on various aspects related to DSEM analyses, such as Bayesian estimation and plotting options. 

## $\triangleright$ N=1 models
Here are the links to the 

* [N=1 data](https://ellenhamaker.github.io/DSEM-demo-videos/Nis1data.dat)

* [Mplus input](https://ellenhamaker.github.io/DSEM-demo-videos/Nis1model.inp)

* [Mplus output](https://ellenhamaker.github.io/DSEM-demo-videos/nis1model.htm)


## $\triangleright$ Multilevel model
In the DSEM demo videos on multilevel DSEM models, these data are used:

* [multilevel data](https://ellenhamaker.github.io/DSEM-demo-videos/Nis1data.dat)

The models that are run as part of the demo video part 1 are:

* Model 1: random means, no random slopes, no random residual variances (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel1.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel1.htm))

* Model 2: random means, random slopes, no random residual variances (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel2.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel2.htm))

* Model 3: random means, random slopes, and residual variances that covary (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel3.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel3.htm))

The models that are run as part of the demo video part 2 are:

* Model 4: random means, slopes, residual variances which are indicators of a latent variable (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel4.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel4.htm))

* Model 5: random means, slopes, residual variances which are predicted by a level 2 predictor (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel5.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel5.htm))

* Model 6: random means, slopes, residual variances which are predicted by a level 2 predictor and that predict a level 2 outcome (Mplus [input](https://ellenhamaker.github.io/DSEM-demo-videos/MLmodel6.inp) and [output](https://ellenhamaker.github.io/DSEM-demo-videos/mlmodel6.htm))


$~$

# Miscellaneous

## $\triangleright$ Bayesian model estimation
Materials to be added later.

## $\triangleright$ Plotting options
Materials to be added later.

## $\triangleright$ TINTERVAL option
Materials to be added later.

## $\triangleright$ Standardized results
Materials to be added later.

---
